//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKurumsalMusteri
    {
        public int KurumsalID { get; set; }
        public string FirmaAd { get; set; }
        public string VKN { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Ulke { get; set; }
        public Nullable<int> Sehir { get; set; }
        public Nullable<int> İlce { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual TblDurum TblDurum { get; set; }
        public virtual TblUlke TblUlke { get; set; }
        public virtual ilceler ilceler { get; set; }
        public virtual iller iller { get; set; }
    }
}
